version: "3.4"

# Development environment override
services:
  php:
    build:
      target: app_php_dev
    volumes:
      - ./back/api:/srv/app
      - ./back/api/docker/php/conf.d/app.dev.ini:/usr/local/etc/php/conf.d/app.dev.ini:ro
      # If you develop on Mac or Windows you can remove the vendor/ directory 
      #  from the bind-mount for better performance by enabling the next line:
      #- /srv/app/vendor
    environment:
      # See https://xdebug.org/docs/all_settings#mode 
      XDEBUG_MODE: "${XDEBUG_MODE:-off}"
    extra_hosts:
      # Ensure that host.docker.internal is correctly defined on Linux
      - host.docker.internal:host-gateway

  pwa:
    image: node:lts-alpine3.16
    working_dir: /srv/app
    volumes:
      - ./front:/srv/app
    environment:
      - ENTRYPOINT_HOST=0.0.0.0
    command: sh -c "npm install && npm run dev"

  caddy:
    volumes:
      - ./back/api/public:/srv/app/public:ro
      - ./back/api/docker/caddy/Caddyfile:/etc/caddy/Caddyfile:ro
    environment:
      MERCURE_EXTRA_DIRECTIVES: demo

  ms-product:
    build: ./back/product
    restart: unless-stopped
    environment:
      - PORT=5000
    volumes:
      - ./back/product:/app
    command: sh -c "yarn && yarn start:dev"

  rabbitmq:
    image: rabbitmq:3.11-management
    ports: 
      - 15672:15672
      - 5672:5672

###> doctrine/doctrine-bundle ###
  database:
    ports:
      - target: 5432
        published: 5432
        protocol: tcp
###< doctrine/doctrine-bundle ###

###> symfony/mercure-bundle ###
###< symfony/mercure-bundle ###
