controllers:
    resource: ../src/Controller/
    type: attribute

kernel:
    resource: ../src/Kernel.php
    type: annotation
    
auth:
    path: /auth
    methods: ['POST']

role_checker:
    path: /role_checker
    methods: ['GET']
    defaults:
        _controller: App\Controller\RoleCheckerController::check
